[package]
name = "minecraft_server"
version = "0.1.0"
authors = ["yuta0801 <yuta030801@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
